<Project>
  <PropertyGroup>
    <!-- Debug and release output path setting -->
    <OutDir>$(SolutionDir)_Output\$(Configuration)\$(TargetFramework)\</OutDir>
    
    <!-- Base intermediate path setting -->
    <BaseIntermediateOutputPath>$(SolutionDir)_Intermediate\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <!-- Intermediate file path setting -->
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>

    <Version>1.0.0.9770</Version>
    <FileVersion>1.0.0.9770</FileVersion>
    <AssemblyVersion>1.0.0.9770</AssemblyVersion>
    <InformationalVersion>1.0.0.26100111</InformationalVersion>
  </PropertyGroup>
</Project>

